# Generated by Django 5.1 on 2024-09-28 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estatemaster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentcommercialadvertisement',
            name='lat',
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentcommercialadvertisement',
            name='lng',
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentdayadvertisement',
            name='lat',
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentdayadvertisement',
            name='lng',
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentlongadvertisement',
            name='lat',
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentlongadvertisement',
            name='lng',
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salecommercialadvertisement',
            name='lat',
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salecommercialadvertisement',
            name='lng',
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saleresidential',
            name='lat',
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saleresidential',
            name='lng',
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
