# Generated by Django 5.1 on 2024-10-26 16:58

import estatemaster.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estatemaster', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisementphoto',
            name='image',
            field=models.ImageField(upload_to=estatemaster.models.advertisement_upload_to),
        ),
    ]
