# Generated by Django 5.0.6 on 2024-05-14 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estatemaster', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
