# Generated by Django 5.0.6 on 2024-06-07 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estatemaster', '0002_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_confirm',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
