# Generated by Django 5.0.6 on 2024-06-08 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estatemaster', '0004_professionalprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professionalprofile',
            name='working_hours',
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='is_macler',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='name_company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='role',
            field=models.CharField(choices=[('realtor', 'Риелтор'), ('agency', 'Агентство'), ('developer', 'Застройщик')], default='realtor', max_length=10),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='specialization_architecture',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='specialization_commercial_rental',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='specialization_commercial_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='specialization_construction',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='specialization_consulting',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='specialization_foreign_rental',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='specialization_foreign_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='specialization_insurance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='specialization_interior_design',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='specialization_mortgage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='specialization_notary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='specialization_property_management',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='specialization_refinancing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='specialization_repair',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='specialization_residential_rental',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='specialization_residential_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='specialization_suburban_rental',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='specialization_suburban_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='working_hours_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='working_hours_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='professionalprofile',
            name='experience',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
