# Generated by Django 5.0.6 on 2024-05-17 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estatemaster', '0005_customuser_delete_user'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
