# Generated by Django 5.0.6 on 2024-06-10 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estatemaster', '0006_rename_name_company_professionalprofile_about_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MortgageSpecialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OtherServiceSpecialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RentalSpecialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SaleSpecialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='professionalprofile',
            name='specialization_commercial_sale',
        ),
        migrations.RemoveField(
            model_name='professionalprofile',
            name='specialization_foreign_sale',
        ),
        migrations.RemoveField(
            model_name='professionalprofile',
            name='specialization_residential_sale',
        ),
        migrations.RemoveField(
            model_name='professionalprofile',
            name='specialization_suburban_sale',
        ),
        migrations.AlterField(
            model_name='professionalprofile',
            name='role',
            field=models.CharField(choices=[('realtor', 'Риелтор'), ('agency', 'Агентство'), ('developer', 'Застройщик')], default='realtor', max_length=10),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='mortgage_specializations',
            field=models.ManyToManyField(blank=True, to='estatemaster.mortgagespecialization'),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='other_service_specializations',
            field=models.ManyToManyField(blank=True, to='estatemaster.otherservicespecialization'),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='rental_specializations',
            field=models.ManyToManyField(blank=True, to='estatemaster.rentalspecialization'),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='sale_specializations',
            field=models.ManyToManyField(blank=True, to='estatemaster.salespecialization'),
        ),
    ]
