# Generated by Django 5.0.6 on 2024-06-10 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estatemaster', '0007_mortgagespecialization_otherservicespecialization_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professionalprofile',
            name='specialization_architecture',
        ),
        migrations.RemoveField(
            model_name='professionalprofile',
            name='specialization_commercial_rental',
        ),
        migrations.RemoveField(
            model_name='professionalprofile',
            name='specialization_construction',
        ),
        migrations.RemoveField(
            model_name='professionalprofile',
            name='specialization_consulting',
        ),
        migrations.RemoveField(
            model_name='professionalprofile',
            name='specialization_foreign_rental',
        ),
        migrations.RemoveField(
            model_name='professionalprofile',
            name='specialization_insurance',
        ),
        migrations.RemoveField(
            model_name='professionalprofile',
            name='specialization_interior_design',
        ),
        migrations.RemoveField(
            model_name='professionalprofile',
            name='specialization_mortgage',
        ),
        migrations.RemoveField(
            model_name='professionalprofile',
            name='specialization_notary',
        ),
        migrations.RemoveField(
            model_name='professionalprofile',
            name='specialization_property_management',
        ),
        migrations.RemoveField(
            model_name='professionalprofile',
            name='specialization_refinancing',
        ),
        migrations.RemoveField(
            model_name='professionalprofile',
            name='specialization_repair',
        ),
        migrations.RemoveField(
            model_name='professionalprofile',
            name='specialization_residential_rental',
        ),
        migrations.RemoveField(
            model_name='professionalprofile',
            name='specialization_suburban_rental',
        ),
    ]
