# Generated by Django 5.0.6 on 2024-06-10 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estatemaster', '0008_remove_professionalprofile_specialization_architecture_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mortgagespecialization',
            options={'verbose_name': 'Ипотечное кредитование', 'verbose_name_plural': 'Ипотечное кредитование'},
        ),
        migrations.AlterModelOptions(
            name='otherservicespecialization',
            options={'verbose_name': 'Другие услуги', 'verbose_name_plural': 'Другие услуги'},
        ),
        migrations.AlterModelOptions(
            name='professionalprofile',
            options={'verbose_name': 'Проф пользователь', 'verbose_name_plural': 'Проф пользователи'},
        ),
        migrations.AlterModelOptions(
            name='rentalspecialization',
            options={'verbose_name': 'Аренда недвижимости', 'verbose_name_plural': 'Аренда недвижимости'},
        ),
        migrations.AlterModelOptions(
            name='salespecialization',
            options={'verbose_name': 'Продажа недвижимости', 'verbose_name_plural': 'Продажа недвижимости'},
        ),
        migrations.RemoveField(
            model_name='professionalprofile',
            name='mortgage_specializations',
        ),
        migrations.RemoveField(
            model_name='professionalprofile',
            name='other_service_specializations',
        ),
        migrations.RemoveField(
            model_name='professionalprofile',
            name='rental_specializations',
        ),
        migrations.RemoveField(
            model_name='professionalprofile',
            name='sale_specializations',
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='mortgage_types',
            field=models.CharField(blank=True, choices=[('ипотека', 'Ипотека'), ('рефинансирование', 'Рефинансирование')], max_length=255),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='other_services',
            field=models.CharField(blank=True, choices=[('страхование', 'Страхование'), ('нотариат', 'Нотариат'), ('управление_объектами', 'Управление объектами'), ('строительство', 'Строительство'), ('консультация', 'Консультация'), ('дизайн_интерьера', 'Дизайн интерьера'), ('ремонт', 'Ремонт'), ('архитектура', 'Архитектура')], max_length=255),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='rental_types',
            field=models.CharField(blank=True, choices=[('жилая', 'Жилая'), ('загородная', 'Загородная'), ('зарубежная', 'Зарубежная'), ('коммерческая', 'Коммерческая')], max_length=255),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='sale_types',
            field=models.CharField(blank=True, choices=[('жилая', 'Жилая'), ('коммерческая', 'Коммерческая'), ('загородная', 'Загородная'), ('зарубежная', 'Зарубежная')], max_length=255),
        ),
    ]
