# Generated by Django 5.0.6 on 2024-06-10 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estatemaster', '0009_alter_mortgagespecialization_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalprofile',
            name='mortgage_types',
            field=models.CharField(blank=True, choices=[('ипотека', 'Ипотека'), ('рефинансирование', 'Рефинансирование')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='professionalprofile',
            name='other_services',
            field=models.CharField(blank=True, choices=[('страхование', 'Страхование'), ('нотариат', 'Нотариат'), ('управление_объектами', 'Управление объектами'), ('строительство', 'Строительство'), ('консультация', 'Консультация'), ('дизайн_интерьера', 'Дизайн интерьера'), ('ремонт', 'Ремонт'), ('архитектура', 'Архитектура')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='professionalprofile',
            name='rental_types',
            field=models.CharField(blank=True, choices=[('жилая', 'Жилая'), ('загородная', 'Загородная'), ('зарубежная', 'Зарубежная'), ('коммерческая', 'Коммерческая')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='professionalprofile',
            name='sale_types',
            field=models.CharField(blank=True, choices=[('жилая', 'Жилая'), ('коммерческая', 'Коммерческая'), ('загородная', 'Загородная'), ('зарубежная', 'Зарубежная')], max_length=255, null=True),
        ),
    ]
