# Generated by Django 5.0.6 on 2024-06-16 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estatemaster', '0011_remove_rentdayadvertisement_promotion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infastructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_wish', models.BooleanField(default=False)),
                ('auto_service', models.BooleanField(default=False)),
                ('pharmacy', models.BooleanField(default=False)),
                ('atelier', models.BooleanField(default=False)),
                ('bank', models.BooleanField(default=False)),
                ('bufet', models.BooleanField(default=False)),
                ('sclad', models.BooleanField(default=False)),
                ('hotel', models.BooleanField(default=False)),
                ('cafe', models.BooleanField(default=False)),
                ('tv_vinema', models.BooleanField(default=False)),
                ('conference', models.BooleanField(default=False)),
                ('med_center', models.BooleanField(default=False)),
                ('mini_market', models.BooleanField(default=False)),
                ('notarial_contore', models.BooleanField(default=False)),
                ('otdel_bank', models.BooleanField(default=False)),
                ('park', models.BooleanField(default=False)),
                ('restoran', models.BooleanField(default=False)),
                ('beaty_salon', models.BooleanField(default=False)),
                ('sclad_place', models.BooleanField(default=False)),
                ('stolov', models.BooleanField(default=False)),
                ('supermarket', models.BooleanField(default=False)),
                ('torg_zona', models.BooleanField(default=False)),
                ('fitness', models.BooleanField(default=False)),
                ('central_recep', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='advertisement',
            options={'verbose_name': 'Объявления', 'verbose_name_plural': 'Объявление'},
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='atelier',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='auto_service',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='auto_wish',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='beaty_salon',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='bufet',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='cafe',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='central_recep',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='conference',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='fitness',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='med_center',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='mini_market',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='notarial_contore',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='otdel_bank',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='park',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='pharmacy',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='restoran',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='sclad',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='sclad_place',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='stolov',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='supermarket',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='torg_zona',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='tv_vinema',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='type_rent_long',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='type_of_rent',
            field=models.CharField(blank=True, choices=[('for_day', 'Посоуточно'), ('for_long', 'Длительно')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='infastructure',
            field=models.ManyToManyField(to='estatemaster.infastructure'),
        ),
    ]
