# Generated by Django 5.0.6 on 2024-06-25 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estatemaster', '0013_remove_advertisement_infastructure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentcommercialadvertisement',
            name='deal_type',
            field=models.CharField(choices=[('rent', 'Аренда')], max_length=100),
        ),
        migrations.AlterField(
            model_name='rentcommercialadvertisement',
            name='type_of_property',
            field=models.CharField(choices=[('commercial', 'Коммерческая')], max_length=50),
        ),
        migrations.AlterField(
            model_name='rentdayadvertisement',
            name='type_of_deal',
            field=models.CharField(choices=[('rent', 'Аренда')], max_length=100),
        ),
        migrations.AlterField(
            model_name='rentlongadvertisement',
            name='deal_type',
            field=models.CharField(choices=[('rent', 'Аренда')], max_length=100),
        ),
        migrations.AlterField(
            model_name='rentlongadvertisement',
            name='type_of_property',
            field=models.CharField(choices=[('residential', 'Жилая')], max_length=50),
        ),
        migrations.AlterField(
            model_name='salecommercialadvertisement',
            name='deal_type',
            field=models.CharField(choices=[('sale', 'Продажа')], max_length=100),
        ),
        migrations.AlterField(
            model_name='salecommercialadvertisement',
            name='type_of_property',
            field=models.CharField(choices=[('commercial', 'Коммерческая')], max_length=50),
        ),
        migrations.AlterField(
            model_name='saleresidential',
            name='deal_type',
            field=models.CharField(choices=[('sale', 'Продажа')], max_length=100),
        ),
        migrations.AlterField(
            model_name='saleresidential',
            name='type_of_property',
            field=models.CharField(choices=[('residential', 'Жилая')], max_length=50),
        ),
    ]
