# Generated by Django 5.0.6 on 2024-07-13 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estatemaster', '0014_alter_rentcommercialadvertisement_deal_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='builder',
            name='address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='builder',
            name='zone',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='saleresidential',
            name='new_or_no',
            field=models.CharField(blank=True, choices=[('second', 'Вторичка'), ('new', 'Новостройка')], default='second', max_length=20),
        ),
        migrations.AlterField(
            model_name='builder',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
