# Generated by Django 5.0.6 on 2024-07-15 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estatemaster', '0016_alter_location_options_alter_saleresidential_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentdayadvertisement',
            name='region',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estatemaster.location'),
        ),
        migrations.AddField(
            model_name='rentlongadvertisement',
            name='region',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estatemaster.location'),
        ),
    ]
