# Generated by Django 5.0.6 on 2024-07-15 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estatemaster', '0017_rentdayadvertisement_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentcommercialadvertisement',
            name='uchastok',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salecommercialadvertisement',
            name='uchastok',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rentcommercialadvertisement',
            name='region',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estatemaster.location'),
        ),
        migrations.AlterField(
            model_name='salecommercialadvertisement',
            name='region',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estatemaster.location'),
        ),
    ]
