# Generated by Django 5.0.6 on 2024-07-15 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estatemaster', '0018_rentcommercialadvertisement_uchastok_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentcommercialadvertisement',
            old_name='count_raint_touch',
            new_name='count_rooms',
        ),
        migrations.RenameField(
            model_name='salecommercialadvertisement',
            old_name='count_raint_touch',
            new_name='count_rooms',
        ),
    ]
