# Generated by Django 5.1 on 2024-08-12 14:44

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estatemaster', '0019_rename_count_raint_touch_rentcommercialadvertisement_count_rooms_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),
        migrations.AlterModelOptions(
            name='saleresidential',
            options={'verbose_name': 'Жилые прожажи', 'verbose_name_plural': 'Жилая продажа'},
        ),
        migrations.RenameField(
            model_name='saleresidential',
            old_name='type_house',
            new_name='houseType',
        ),
        migrations.RenameField(
            model_name='saleresidential',
            old_name='count_rooms',
            new_name='roomsNumber',
        ),
        migrations.RemoveField(
            model_name='saleresidential',
            name='account_type',
        ),
        migrations.RemoveField(
            model_name='saleresidential',
            name='deal_type',
        ),
        migrations.RemoveField(
            model_name='saleresidential',
            name='entrance',
        ),
        migrations.RemoveField(
            model_name='saleresidential',
            name='how_sale',
        ),
        migrations.RemoveField(
            model_name='saleresidential',
            name='property_type',
        ),
        migrations.RemoveField(
            model_name='saleresidential',
            name='type_of_property',
        ),
        migrations.RemoveField(
            model_name='saleresidential',
            name='view_from_window',
        ),
        migrations.AddField(
            model_name='saleresidential',
            name='accountType',
            field=models.CharField(blank=True, choices=[('owner', 'Собственник'), ('agent', 'Агент')], default='owner', max_length=20),
        ),
        migrations.AddField(
            model_name='saleresidential',
            name='apartmentEntrance',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('ramp', 'Пандус'), ('garbage_chute', 'Мусоропровод')], max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='saleresidential',
            name='dealType',
            field=models.CharField(blank=True, choices=[('sale', 'Продажа'), ('rent', 'Аренда')], default='sale', max_length=100),
        ),
        migrations.AddField(
            model_name='saleresidential',
            name='estateType',
            field=models.CharField(blank=True, choices=[('residential', 'Жилая'), ('commercial', 'Коммерческая')], max_length=50),
        ),
        migrations.AddField(
            model_name='saleresidential',
            name='propertyType',
            field=models.CharField(blank=True, choices=[('flat', 'Квартира'), ('apartment', 'Апартаменты')], max_length=30),
        ),
        migrations.AddField(
            model_name='saleresidential',
            name='saleType',
            field=models.CharField(blank=True, choices=[('only_sale', 'Только продаю'), ('sale_another', 'Одновременно покупаю другую')], max_length=50),
        ),
        migrations.AddField(
            model_name='saleresidential',
            name='viewFromWindow',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('outside', 'На улицу'), ('into_the_courtyard', 'Во двор'), ('to_sea', 'На море')], max_length=33, null=True),
        ),
        migrations.AlterField(
            model_name='saleresidential',
            name='ceiling_height',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
