# Generated by Django 5.1 on 2024-08-12 15:45

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estatemaster', '0020_alter_location_options_alter_saleresidential_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rentlongadvertisement',
            options={'verbose_name': 'Аренда длительная продажа', 'verbose_name_plural': 'Аренда длительная продажа'},
        ),
        migrations.RenameField(
            model_name='rentlongadvertisement',
            old_name='property_type',
            new_name='propertyType',
        ),
        migrations.RenameField(
            model_name='rentlongadvertisement',
            old_name='count_rooms',
            new_name='roomsNumber',
        ),
        migrations.RenameField(
            model_name='rentlongadvertisement',
            old_name='shetchik',
            new_name='utility_payer',
        ),
        migrations.RemoveField(
            model_name='rentlongadvertisement',
            name='account_type',
        ),
        migrations.RemoveField(
            model_name='rentlongadvertisement',
            name='bathroom',
        ),
        migrations.RemoveField(
            model_name='rentlongadvertisement',
            name='bathroom_doosh',
        ),
        migrations.RemoveField(
            model_name='rentlongadvertisement',
            name='bathroom_joint',
        ),
        migrations.RemoveField(
            model_name='rentlongadvertisement',
            name='bathroom_vanna',
        ),
        migrations.RemoveField(
            model_name='rentlongadvertisement',
            name='deal_type',
        ),
        migrations.RemoveField(
            model_name='rentlongadvertisement',
            name='entrance',
        ),
        migrations.RemoveField(
            model_name='rentlongadvertisement',
            name='holodilnik',
        ),
        migrations.RemoveField(
            model_name='rentlongadvertisement',
            name='internet',
        ),
        migrations.RemoveField(
            model_name='rentlongadvertisement',
            name='living_animal',
        ),
        migrations.RemoveField(
            model_name='rentlongadvertisement',
            name='living_baby',
        ),
        migrations.RemoveField(
            model_name='rentlongadvertisement',
            name='mebel_kitchen',
        ),
        migrations.RemoveField(
            model_name='rentlongadvertisement',
            name='mebel_rooms',
        ),
        migrations.RemoveField(
            model_name='rentlongadvertisement',
            name='phone_house',
        ),
        migrations.RemoveField(
            model_name='rentlongadvertisement',
            name='posud_car',
        ),
        migrations.RemoveField(
            model_name='rentlongadvertisement',
            name='split',
        ),
        migrations.RemoveField(
            model_name='rentlongadvertisement',
            name='stiral_car',
        ),
        migrations.RemoveField(
            model_name='rentlongadvertisement',
            name='tv',
        ),
        migrations.RemoveField(
            model_name='rentlongadvertisement',
            name='type_of_property',
        ),
        migrations.RemoveField(
            model_name='rentlongadvertisement',
            name='view_from_window',
        ),
        migrations.RemoveField(
            model_name='rentlongadvertisement',
            name='without_mebel',
        ),
        migrations.AddField(
            model_name='rentlongadvertisement',
            name='accountType',
            field=models.CharField(blank=True, choices=[('owner', 'Собственник'), ('agent', 'Агент')], default='owner', max_length=20),
        ),
        migrations.AddField(
            model_name='rentlongadvertisement',
            name='apartmentEntrance',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('ramp', 'Пандус'), ('garbage_chute', 'Мусоропровод')], max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='rentlongadvertisement',
            name='bathroom_choice',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('bath', 'Ванна'), ('shower', 'Душевая кабина')], max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='rentlongadvertisement',
            name='bathroom_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество ванных комнат'),
        ),
        migrations.AddField(
            model_name='rentlongadvertisement',
            name='bathroom_joint_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество совмещенных ванных комнат'),
        ),
        migrations.AddField(
            model_name='rentlongadvertisement',
            name='communication',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('internet', 'Интернет'), ('phone', 'Телефон')], max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='rentlongadvertisement',
            name='currency',
            field=models.CharField(choices=[('mzn', 'MZN'), ('usd', 'USD'), ('eur', 'EUR')], default='mzn', max_length=3),
        ),
        migrations.AddField(
            model_name='rentlongadvertisement',
            name='dealType',
            field=models.CharField(blank=True, choices=[('sale', 'Продажа'), ('rent', 'Аренда')], default='sale', max_length=100),
        ),
        migrations.AddField(
            model_name='rentlongadvertisement',
            name='estateType',
            field=models.CharField(blank=True, choices=[('residential', 'Жилая'), ('commercial', 'Коммерческая')], max_length=50),
        ),
        migrations.AddField(
            model_name='rentlongadvertisement',
            name='furniture',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('no_furniture', 'Без мебели'), ('kitchen', 'На кухне'), ('rooms', 'В комнатах')], max_length=26, null=True),
        ),
        migrations.AddField(
            model_name='rentlongadvertisement',
            name='living_conditions',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('children_allowed', 'Можно с детьми'), ('pets_allowed', 'Можно с животными')], max_length=29, null=True, verbose_name='Условия проживания'),
        ),
        migrations.AddField(
            model_name='rentlongadvertisement',
            name='new_or_no',
            field=models.CharField(blank=True, choices=[('second', 'Вторичка'), ('new', 'Новостройка')], default='second', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='rentlongadvertisement',
            name='tech',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('ac', 'Кондиционер'), ('fridge', 'Холодильник'), ('tv', 'Телевизор'), ('dishwasher', 'Посудомоечная машина'), ('washing_machine', 'Стиральная машина')], max_length=39, null=True),
        ),
        migrations.AddField(
            model_name='rentlongadvertisement',
            name='viewFromWindow',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('outside', 'На улицу'), ('into_the_courtyard', 'Во двор'), ('to_sea', 'На море')], max_length=33, null=True),
        ),
        migrations.AlterField(
            model_name='rentlongadvertisement',
            name='prepayment',
            field=models.CharField(choices=[('1_month', 'За 1 месяц'), ('2_months', '2 месяца'), ('3_months', '3 месяца'), ('4_plus', '4+')], max_length=70),
        ),
        migrations.AlterField(
            model_name='rentlongadvertisement',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estatemaster.location'),
        ),
        migrations.AlterField(
            model_name='saleresidential',
            name='new_or_no',
            field=models.CharField(blank=True, choices=[('second', 'Вторичка'), ('new', 'Новостройка')], default='second', max_length=20, null=True),
        ),
    ]
