# Generated by Django 5.1 on 2024-08-18 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estatemaster', '0024_rename_age_build_rentcommercialadvertisement_agebuild_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saleresidential',
            old_name='ceiling_height',
            new_name='ceilingHeight',
        ),
        migrations.RenameField(
            model_name='saleresidential',
            old_name='bathroom',
            new_name='combinedBathroom',
        ),
        migrations.RenameField(
            model_name='saleresidential',
            old_name='number_flat',
            new_name='flatNumber',
        ),
        migrations.RenameField(
            model_name='saleresidential',
            old_name='floors_house',
            new_name='floorsHouse',
        ),
        migrations.RenameField(
            model_name='saleresidential',
            old_name='bathroom_joint',
            new_name='freightElevator',
        ),
        migrations.RenameField(
            model_name='saleresidential',
            old_name='age_build',
            new_name='kitchenArea',
        ),
        migrations.RenameField(
            model_name='saleresidential',
            old_name='kitchen_area',
            new_name='livingArea',
        ),
        migrations.RenameField(
            model_name='saleresidential',
            old_name='minute_stop',
            new_name='minutesBusStop',
        ),
        migrations.RenameField(
            model_name='saleresidential',
            old_name='nearest_stop',
            new_name='nearestStop',
        ),
        migrations.RenameField(
            model_name='saleresidential',
            old_name='elevators_cargo',
            new_name='passengerElevator',
        ),
        migrations.RenameField(
            model_name='saleresidential',
            old_name='transport',
            new_name='pathType',
        ),
        migrations.RenameField(
            model_name='saleresidential',
            old_name='elevators_passengers',
            new_name='separateBathroom',
        ),
        migrations.RenameField(
            model_name='saleresidential',
            old_name='headings',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='saleresidential',
            old_name='total_area',
            new_name='totalArea',
        ),
        migrations.RenameField(
            model_name='saleresidential',
            old_name='living_area',
            new_name='yaerBuilt',
        ),
        migrations.RenameField(
            model_name='saleresidential',
            old_name='video',
            new_name='youtubeLink',
        ),
    ]
