# Generated by Django 5.1 on 2024-08-19 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estatemaster', '0025_rename_ceiling_height_saleresidential_ceilingheight_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleresidential',
            name='new_or_no',
        ),
        migrations.RemoveField(
            model_name='saleresidential',
            name='photo',
        ),
        migrations.AlterField(
            model_name='saleresidential',
            name='flatNumber',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='saleresidential',
            name='minutesBusStop',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
