# Generated by Django 5.1 on 2024-08-19 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estatemaster', '0027_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MortgageSpecialization',
        ),
        migrations.DeleteModel(
            name='OtherServiceSpecialization',
        ),
        migrations.DeleteModel(
            name='RentalSpecialization',
        ),
        migrations.DeleteModel(
            name='SaleSpecialization',
        ),
    ]
