# Generated by Django 5.1 on 2024-08-19 14:51

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estatemaster', '0028_delete_mortgagespecialization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleresidential',
            name='address',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='saleresidential',
            name='apartmentEntrance',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('ramp', 'Пандус'), ('trashChute', 'Мусоропровод')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='saleresidential',
            name='houseType',
            field=models.CharField(choices=[('brick', 'Кирпичный'), ('monolithic', 'Монолитный'), ('panel', 'Панельный'), ('block', 'Блочный'), ('wooden', 'Деревянный')], max_length=100),
        ),
        migrations.AlterField(
            model_name='saleresidential',
            name='obj',
            field=models.CharField(choices=[('flat', 'Квартира'), ('flatNewBuilding', 'Квартира в новостройке'), ('room', 'Комната'), ('flatShare', 'Доля в квартире'), ('house', 'Дом'), ('cottage', 'Коттедж'), ('tanhouse', 'Таунхаус'), ('partHouse', 'Часть дома'), ('plot', 'Участок')], max_length=100),
        ),
        migrations.AlterField(
            model_name='saleresidential',
            name='parking',
            field=models.CharField(blank=True, choices=[('ground', 'Наземная'), ('multilevel', 'Многоуровневая'), ('underground', 'Подземная'), ('rooftop', 'На крыше')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='saleresidential',
            name='pathType',
            field=models.CharField(choices=[('foot', 'Пешком'), ('transport', 'Транспорт')], default='afoot', max_length=20),
        ),
        migrations.AlterField(
            model_name='saleresidential',
            name='propertyType',
            field=models.CharField(blank=True, choices=[('flat', 'Квартира'), ('apartments', 'Апартаменты')], max_length=30),
        ),
        migrations.AlterField(
            model_name='saleresidential',
            name='repair',
            field=models.CharField(blank=True, choices=[('unrepaired', 'Без ремонта'), ('cosmetic', 'Косметический'), ('euro', 'Евро'), ('designer', 'Дизайнерский')], max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='saleresidential',
            name='roomsNumber',
            field=models.CharField(choices=[('studio', 'Студия'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('overSix', '6'), ('freePlanning', 'Свободная планировка')], max_length=20),
        ),
        migrations.AlterField(
            model_name='saleresidential',
            name='saleType',
            field=models.CharField(blank=True, choices=[('onlySale', 'Только продаю'), ('buyingAnother', 'Одновременно покупаю другую')], max_length=50),
        ),
        migrations.AlterField(
            model_name='saleresidential',
            name='viewFromWindow',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('outside', 'На улицу'), ('courtyard', 'Во двор'), ('atSea', 'На море')], max_length=23, null=True),
        ),
    ]
