# Generated by Django 5.1 on 2024-08-19 15:39

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estatemaster', '0029_alter_saleresidential_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentlongadvertisement',
            old_name='elevators_cargo',
            new_name='combinedBathroom',
        ),
        migrations.RenameField(
            model_name='rentlongadvertisement',
            old_name='floors_house',
            new_name='floorsHouse',
        ),
        migrations.RenameField(
            model_name='rentlongadvertisement',
            old_name='elevators_passengers',
            new_name='freightElevator',
        ),
        migrations.RenameField(
            model_name='rentlongadvertisement',
            old_name='kitchen_area',
            new_name='kitchenArea',
        ),
        migrations.RenameField(
            model_name='rentlongadvertisement',
            old_name='living_area',
            new_name='livingArea',
        ),
        migrations.RenameField(
            model_name='rentlongadvertisement',
            old_name='minute_stop',
            new_name='nearestStop',
        ),
        migrations.RenameField(
            model_name='rentlongadvertisement',
            old_name='video',
            new_name='youtubeLink',
        ),
        migrations.RemoveField(
            model_name='rentlongadvertisement',
            name='bathroom_count',
        ),
        migrations.RemoveField(
            model_name='rentlongadvertisement',
            name='bathroom_joint_count',
        ),
        migrations.RemoveField(
            model_name='rentlongadvertisement',
            name='nearest_stop',
        ),
        migrations.RemoveField(
            model_name='rentlongadvertisement',
            name='new_or_no',
        ),
        migrations.RemoveField(
            model_name='rentlongadvertisement',
            name='number_flat',
        ),
        migrations.RemoveField(
            model_name='rentlongadvertisement',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='rentlongadvertisement',
            name='total_area',
        ),
        migrations.RemoveField(
            model_name='rentlongadvertisement',
            name='transport',
        ),
        migrations.RemoveField(
            model_name='rentlongadvertisement',
            name='type_rent_long',
        ),
        migrations.AddField(
            model_name='rentlongadvertisement',
            name='flatNumber',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='rentlongadvertisement',
            name='leaseType',
            field=models.CharField(blank=True, choices=[('long', 'Длительно'), ('daily', 'Посуточно')], max_length=70),
        ),
        migrations.AddField(
            model_name='rentlongadvertisement',
            name='minutesBusStop',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='rentlongadvertisement',
            name='passengerElevator',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rentlongadvertisement',
            name='pathType',
            field=models.CharField(choices=[('foot', 'Пешком'), ('transport', 'Транспорт')], default='foot', max_length=20),
        ),
        migrations.AddField(
            model_name='rentlongadvertisement',
            name='separateBathroom',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rentlongadvertisement',
            name='totalArea',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='rentlongadvertisement',
            name='address',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='rentlongadvertisement',
            name='apartmentEntrance',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('ramp', 'Пандус'), ('trashChute', 'Мусоропровод')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='rentlongadvertisement',
            name='obj',
            field=models.CharField(choices=[('flat', 'Квартира'), ('flatNewBuilding', 'Квартира в новостройке'), ('room', 'Комната'), ('flatShare', 'Доля в квартире'), ('house', 'Дом'), ('cottage', 'Коттедж'), ('tanhouse', 'Таунхаус'), ('partHouse', 'Часть дома'), ('plot', 'Участок')], max_length=100),
        ),
        migrations.AlterField(
            model_name='rentlongadvertisement',
            name='parking',
            field=models.CharField(blank=True, choices=[('ground', 'Наземная'), ('multilevel', 'Многоуровневая'), ('underground', 'Подземная'), ('rooftop', 'На крыше')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='rentlongadvertisement',
            name='propertyType',
            field=models.CharField(choices=[('flat', 'Квартира'), ('apartments', 'Апартаменты')], max_length=30),
        ),
        migrations.AlterField(
            model_name='rentlongadvertisement',
            name='repair',
            field=models.CharField(blank=True, choices=[('unrepaired', 'Без ремонта'), ('cosmetic', 'Косметический'), ('euro', 'Евро'), ('designer', 'Дизайнерский')], max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='rentlongadvertisement',
            name='roomsNumber',
            field=models.CharField(choices=[('studio', 'Студия'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('overSix', '6'), ('freePlanning', 'Свободная планировка')], max_length=20),
        ),
        migrations.AlterField(
            model_name='rentlongadvertisement',
            name='viewFromWindow',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('outside', 'На улицу'), ('courtyard', 'Во двор'), ('atSea', 'На море')], max_length=23, null=True),
        ),
        migrations.AlterField(
            model_name='saleresidential',
            name='parking',
            field=models.CharField(blank=True, choices=[('ground', 'Наземная'), ('multiLevel', 'Многоуровневая'), ('underground', 'Подземная'), ('rooftop', 'На крыше')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='saleresidential',
            name='pathType',
            field=models.CharField(choices=[('foot', 'Пешком'), ('transport', 'Транспорт')], default='foot', max_length=20),
        ),
    ]
