# Generated by Django 5.1 on 2024-08-19 15:55

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estatemaster', '0030_rename_elevators_cargo_rentlongadvertisement_combinedbathroom_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentlongadvertisement',
            old_name='headings',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='rentlongadvertisement',
            name='promotion',
        ),
        migrations.AlterField(
            model_name='rentlongadvertisement',
            name='furniture',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('noFurniture', 'Без мебели'), ('kitchen', 'На кухне'), ('rooms', 'В комнатах')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='rentlongadvertisement',
            name='parking',
            field=models.CharField(blank=True, choices=[('ground', 'Наземная'), ('multiLevel', 'Многоуровневая'), ('underground', 'Подземная'), ('rooftop', 'На крыше')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='saleresidential',
            name='phone',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='saleresidential',
            name='whatsapp',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
