# Generated by Django 5.1 on 2024-08-19 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estatemaster', '0031_rename_headings_rentlongadvertisement_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleresidential',
            name='houseType',
            field=models.CharField(blank=True, choices=[('brick', 'Кирпичный'), ('monolithic', 'Монолитный'), ('panel', 'Панельный'), ('block', 'Блочный'), ('wooden', 'Деревянный')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='saleresidential',
            name='nearestStop',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
