# Generated by Django 5.1 on 2024-08-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estatemaster', '0033_alter_saleresidential_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentlongadvertisement',
            name='minutesBusStop',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rentlongadvertisement',
            name='nearestStop',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
