# Generated by Django 5.1 on 2024-08-22 21:25

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estatemaster', '0034_alter_rentlongadvertisement_minutesbusstop_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentlongadvertisement',
            old_name='communication',
            new_name='connection',
        ),
        migrations.RenameField(
            model_name='rentlongadvertisement',
            old_name='utility_payer',
            new_name='utilityPayment',
        ),
        migrations.RenameField(
            model_name='rentlongadvertisement',
            old_name='additional_phone',
            new_name='whatsApp',
        ),
        migrations.RemoveField(
            model_name='rentlongadvertisement',
            name='bathroom_choice',
        ),
        migrations.RemoveField(
            model_name='rentlongadvertisement',
            name='communication_method',
        ),
        migrations.RemoveField(
            model_name='rentlongadvertisement',
            name='living_conditions',
        ),
        migrations.RemoveField(
            model_name='rentlongadvertisement',
            name='prepayment',
        ),
        migrations.RemoveField(
            model_name='rentlongadvertisement',
            name='rental_period',
        ),
        migrations.RemoveField(
            model_name='rentlongadvertisement',
            name='tech',
        ),
        migrations.AddField(
            model_name='rentlongadvertisement',
            name='apartment',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('conditioner', 'Кондиционер'), ('fridge', 'Холодильник'), ('tv', 'Телевизор'), ('dishwasher', 'Посудомоечная машина'), ('washingmMachine', 'Стиральная машина')], max_length=48, null=True),
        ),
        migrations.AddField(
            model_name='rentlongadvertisement',
            name='bathroom',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('bath', 'Ванна'), ('showerRoom', 'Душевая кабина')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='rentlongadvertisement',
            name='currency_per_month',
            field=models.CharField(choices=[('mzn', 'MZN'), ('usd', 'USD'), ('eur', 'EUR')], default='mzn', max_length=3),
        ),
        migrations.AddField(
            model_name='rentlongadvertisement',
            name='livingConditions',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('allowed_with_children', 'Можно с детьми'), ('allowed_with_pets', 'Можно с животными')], max_length=39, null=True, verbose_name='Условия проживания'),
        ),
        migrations.AddField(
            model_name='rentlongadvertisement',
            name='prepaymentPeriod',
            field=models.CharField(blank=True, choices=[('1_month', 'За 1 месяц'), ('2_months', '2 месяца'), ('3_months', '3 месяца'), ('4+_months', '4+')], max_length=70),
        ),
        migrations.AddField(
            model_name='rentlongadvertisement',
            name='rentalTerm',
            field=models.CharField(choices=[('several_months', 'Несколько месяцев'), ('year', 'От года')], max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='rentlongadvertisement',
            name='furniture',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('noFurniture', 'Без мебели'), ('inKitchen', 'На кухне'), ('inRooms', 'В комнатах')], max_length=29, null=True),
        ),
    ]
