# Generated by Django 5.1 on 2024-08-23 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estatemaster', '0036_advertisementphoto_delete_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdvertisementPhoto',
        ),
    ]
