# Generated by Django 5.1 on 2024-08-23 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estatemaster', '0038_advertisementphoto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdvertisementPhoto',
        ),
    ]
