# Generated by Django 5.1 on 2024-08-24 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estatemaster', '0040_advertisementphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisementphoto',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
