# Generated by Django 5.1 on 2024-08-24 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('estatemaster', '0041_alter_advertisementphoto_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisementphoto',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
