# Generated by Django 5.1 on 2024-08-24 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estatemaster', '0042_alter_advertisementphoto_content_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentdayadvertisement',
            name='new_or_no',
        ),
    ]
