# Generated by Django 5.1 on 2024-08-24 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estatemaster', '0043_remove_rentdayadvertisement_new_or_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleresidential',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
