# Generated by Django 5.1 on 2024-08-24 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estatemaster', '0044_saleresidential_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleresidential',
            name='apartmentEntrance',
            field=models.CharField(blank=True, choices=[('ramp', 'Пандус'), ('trashChute', 'Мусоропровод')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='saleresidential',
            name='viewFromWindow',
            field=models.CharField(blank=True, choices=[('outside', 'На улицу'), ('courtyard', 'Во двор'), ('atSea', 'На море')], max_length=10, null=True),
        ),
    ]
