# Generated by Django 5.1 on 2024-08-24 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estatemaster', '0045_alter_saleresidential_apartmententrance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentlongadvertisement',
            name='apartmentEntrance',
            field=models.CharField(blank=True, choices=[('ramp', 'Пандус'), ('trashChute', 'Мусоропровод')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='rentlongadvertisement',
            name='livingConditions',
            field=models.CharField(blank=True, choices=[('allowed_with_children', 'Можно с детьми'), ('allowed_with_pets', 'Можно с животными')], max_length=100, null=True, verbose_name='Условия проживания'),
        ),
        migrations.AlterField(
            model_name='rentlongadvertisement',
            name='viewFromWindow',
            field=models.CharField(blank=True, choices=[('outside', 'На улицу'), ('courtyard', 'Во двор'), ('atSea', 'На море')], max_length=10, null=True),
        ),
    ]
