# Generated by Django 5.1 on 2024-08-25 14:03

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estatemaster', '0046_alter_rentlongadvertisement_apartmententrance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentdayadvertisement',
            old_name='floors_house',
            new_name='flatNumber',
        ),
        migrations.RenameField(
            model_name='rentdayadvertisement',
            old_name='headings',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='rentdayadvertisement',
            old_name='guest_count',
            new_name='totalArea',
        ),
        migrations.RenameField(
            model_name='rentdayadvertisement',
            old_name='video',
            new_name='youtubeLink',
        ),
        migrations.RemoveField(
            model_name='rentdayadvertisement',
            name='kitchen_area',
        ),
        migrations.RemoveField(
            model_name='rentdayadvertisement',
            name='number_flat',
        ),
        migrations.RemoveField(
            model_name='rentdayadvertisement',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='rentdayadvertisement',
            name='promotion',
        ),
        migrations.RemoveField(
            model_name='rentdayadvertisement',
            name='total_area',
        ),
        migrations.RemoveField(
            model_name='rentdayadvertisement',
            name='type_rent_long',
        ),
        migrations.AddField(
            model_name='rentdayadvertisement',
            name='floorsHouse',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentdayadvertisement',
            name='kitchenArea',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentdayadvertisement',
            name='leaseType',
            field=models.CharField(blank=True, choices=[('long', 'Длительно'), ('daily', 'Посуточно')], max_length=70),
        ),
        migrations.AddField(
            model_name='rentdayadvertisement',
            name='livingArea',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentdayadvertisement',
            name='minutesBusStop',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='rentdayadvertisement',
            name='nearestStop',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='rentdayadvertisement',
            name='pathType',
            field=models.CharField(choices=[('foot', 'Пешком'), ('transport', 'Транспорт')], default='foot', max_length=20),
        ),
        migrations.AlterField(
            model_name='rentdayadvertisement',
            name='address',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='rentdayadvertisement',
            name='bathroom_choice',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('bath', 'Ванна'), ('showerRoom', 'Душевая кабина')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='rentdayadvertisement',
            name='floor',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='rentdayadvertisement',
            name='furniture',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('noFurniture', 'Без мебели'), ('inKitchen', 'На кухне'), ('inRooms', 'В комнатах')], max_length=29, null=True),
        ),
        migrations.AlterField(
            model_name='rentdayadvertisement',
            name='living_conditions',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('allowed_with_children', 'Можно с детьми'), ('allowed_with_pets', 'Можно с животными')], max_length=39, null=True, verbose_name='Условия проживания'),
        ),
        migrations.AlterField(
            model_name='rentdayadvertisement',
            name='minute_stop',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='rentdayadvertisement',
            name='nearest_stop',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='rentdayadvertisement',
            name='propertyType',
            field=models.CharField(choices=[('flat', 'Квартира'), ('apartments', 'Апартаменты')], max_length=30),
        ),
        migrations.AlterField(
            model_name='rentdayadvertisement',
            name='roomsNumber',
            field=models.CharField(choices=[('studio', 'Студия'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('overSix', '6'), ('freePlanning', 'Свободная планировка')], max_length=20),
        ),
        migrations.AlterField(
            model_name='rentdayadvertisement',
            name='tech',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('conditioner', 'Кондиционер'), ('fridge', 'Холодильник'), ('tv', 'Телевизор'), ('dishwasher', 'Посудомоечная машина'), ('washingmMachine', 'Стиральная машина')], max_length=48, null=True),
        ),
    ]
