# Generated by Django 5.1 on 2024-08-25 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estatemaster', '0048_rename_agebuild_salecommercialadvertisement_buildingarea_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentdayadvertisement',
            name='daily_price_currency',
            field=models.CharField(blank=True, choices=[('MZN', 'MZN'), ('USD', 'USD'), ('EUR', 'EUR')], default='mzn', max_length=3),
        ),
        migrations.AlterField(
            model_name='rentdayadvertisement',
            name='deposit_currency',
            field=models.CharField(blank=True, choices=[('MZN', 'MZN'), ('USD', 'USD'), ('EUR', 'EUR')], default='mzn', max_length=3),
        ),
        migrations.AlterField(
            model_name='rentlongadvertisement',
            name='currency',
            field=models.CharField(choices=[('MZN', 'MZN'), ('USD', 'USD'), ('EUR', 'EUR')], default='mzn', max_length=3),
        ),
        migrations.AlterField(
            model_name='rentlongadvertisement',
            name='currency_per_month',
            field=models.CharField(choices=[('MZN', 'MZN'), ('USD', 'USD'), ('EUR', 'EUR')], default='mzn', max_length=3),
        ),
        migrations.AlterField(
            model_name='salecommercialadvertisement',
            name='currency_per',
            field=models.CharField(choices=[('MZN', 'MZN'), ('USD', 'Доллар'), ('EUR', 'Евро')], default='mzn', max_length=3),
        ),
        migrations.AlterField(
            model_name='salecommercialadvertisement',
            name='currency_total',
            field=models.CharField(choices=[('MZN', 'MZN'), ('USD', 'Доллар'), ('EUR', 'Евро')], default='mzn', max_length=3),
        ),
        migrations.AlterField(
            model_name='salecommercialadvertisement',
            name='parkingCurreny',
            field=models.CharField(choices=[('MZN', 'MZN'), ('USD', 'Доллар'), ('EUR', 'Евро')], default='mzn', max_length=3),
        ),
        migrations.AlterField(
            model_name='saleresidential',
            name='currency',
            field=models.CharField(choices=[('MZN', 'MZN'), ('USD', 'Доллар'), ('EUR', 'Евро')], default='mzn', max_length=3),
        ),
    ]
