# Generated by Django 5.1 on 2024-08-25 15:21

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estatemaster', '0049_alter_rentdayadvertisement_daily_price_currency_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentcommercialadvertisement',
            old_name='ageBuild',
            new_name='buildingArea',
        ),
        migrations.RenameField(
            model_name='rentcommercialadvertisement',
            old_name='klassBuild',
            new_name='buildingClass',
        ),
        migrations.RenameField(
            model_name='rentcommercialadvertisement',
            old_name='name_building',
            new_name='buildingName',
        ),
        migrations.RenameField(
            model_name='rentcommercialadvertisement',
            old_name='areaBuild',
            new_name='ceilingHeights',
        ),
        migrations.RenameField(
            model_name='rentcommercialadvertisement',
            old_name='buildDeveloper',
            new_name='developer',
        ),
        migrations.RenameField(
            model_name='rentcommercialadvertisement',
            old_name='floors_house',
            new_name='floorsHouse',
        ),
        migrations.RenameField(
            model_name='rentcommercialadvertisement',
            old_name='buildManagmentCompany',
            new_name='managementCompany',
        ),
        migrations.RenameField(
            model_name='rentcommercialadvertisement',
            old_name='min_rent_period',
            new_name='minimumLeaseTerm',
        ),
        migrations.RenameField(
            model_name='rentcommercialadvertisement',
            old_name='rent_holidays',
            new_name='operatingCosts',
        ),
        migrations.RenameField(
            model_name='rentcommercialadvertisement',
            old_name='headings',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='rentcommercialadvertisement',
            old_name='total_area',
            new_name='totalArea',
        ),
        migrations.RenameField(
            model_name='rentcommercialadvertisement',
            old_name='ceiling_height',
            new_name='yearBuilt',
        ),
        migrations.RenameField(
            model_name='rentcommercialadvertisement',
            old_name='video',
            new_name='youtubeLink',
        ),
        migrations.RemoveField(
            model_name='rentcommercialadvertisement',
            name='agent_bonus',
        ),
        migrations.RemoveField(
            model_name='rentcommercialadvertisement',
            name='buildCategory',
        ),
        migrations.RemoveField(
            model_name='rentcommercialadvertisement',
            name='buildConditioning',
        ),
        migrations.RemoveField(
            model_name='rentcommercialadvertisement',
            name='buildFireStop',
        ),
        migrations.RemoveField(
            model_name='rentcommercialadvertisement',
            name='buildHeating',
        ),
        migrations.RemoveField(
            model_name='rentcommercialadvertisement',
            name='buildInfo',
        ),
        migrations.RemoveField(
            model_name='rentcommercialadvertisement',
            name='buildVentilation',
        ),
        migrations.RemoveField(
            model_name='rentcommercialadvertisement',
            name='communal_payments',
        ),
        migrations.RemoveField(
            model_name='rentcommercialadvertisement',
            name='minute_stop',
        ),
        migrations.RemoveField(
            model_name='rentcommercialadvertisement',
            name='nearest_stop',
        ),
        migrations.RemoveField(
            model_name='rentcommercialadvertisement',
            name='operating_costs',
        ),
        migrations.RemoveField(
            model_name='rentcommercialadvertisement',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='rentcommercialadvertisement',
            name='plotBuild',
        ),
        migrations.RemoveField(
            model_name='rentcommercialadvertisement',
            name='rent_type',
        ),
        migrations.RemoveField(
            model_name='rentcommercialadvertisement',
            name='transport',
        ),
        migrations.RemoveField(
            model_name='rentcommercialadvertisement',
            name='typeBuilding',
        ),
        migrations.AddField(
            model_name='rentcommercialadvertisement',
            name='agentBonus',
            field=models.CharField(choices=[('none', 'Нет'), ('fixed_sum', 'Фиксированная сумма'), ('percentage_of_deal', 'Процент от сделки')], default='false', max_length=50),
        ),
        migrations.AddField(
            model_name='rentcommercialadvertisement',
            name='buildingType',
            field=models.CharField(blank=True, choices=[('administrative_building', 'Административное здание'), ('business_center', 'Бизнес-центр'), ('shopping_center', 'Торговый центр'), ('warehouse_complex', 'Складской комплекс'), ('industrial_park', 'Промышленный парк'), ('production_complex', 'Производственный комплекс'), ('multifunctional_complex', 'Многофункциональный комплекс'), ('logistics_complex', 'Логистический комплекс'), ('outlet', 'Аутлет'), ('other', 'Другое')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='rentcommercialadvertisement',
            name='category',
            field=models.CharField(blank=True, choices=[('valid', 'Действующее'), ('project', 'Проект'), ('under_construction', 'Строящееся')], max_length=30),
        ),
        migrations.AddField(
            model_name='rentcommercialadvertisement',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rentcommercialadvertisement',
            name='fireExtinguishingSystem',
            field=models.CharField(blank=True, choices=[('hydrant', 'Гидрантная'), ('sprinkler', 'Спринклерная'), ('powder', 'Порошковая'), ('gas', 'Газовая'), ('alarm', 'Сигнализация'), ('false', 'Нет')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='rentcommercialadvertisement',
            name='heating',
            field=models.CharField(blank=True, choices=[('autonomous', 'Автономное'), ('center', 'Центральное'), ('none', 'Нет')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='rentcommercialadvertisement',
            name='minutesBusStop',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='rentcommercialadvertisement',
            name='nearestStop',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='rentcommercialadvertisement',
            name='pathType',
            field=models.CharField(choices=[('foot', 'Пешком'), ('transport', 'Транспорт')], default='foot', max_length=20),
        ),
        migrations.AddField(
            model_name='rentcommercialadvertisement',
            name='plot',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='rentcommercialadvertisement',
            name='rentalHolidays',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentcommercialadvertisement',
            name='rentalType',
            field=models.CharField(blank=True, choices=[('long-term', 'Долгосрочная'), ('short-term', 'Краткосрочная')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rentcommercialadvertisement',
            name='utilityPayment',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentcommercialadvertisement',
            name='ventilation',
            field=models.CharField(blank=True, choices=[('natural', 'Естественная'), ('inflow', 'Приточная'), ('none', 'Нет')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='rentcommercialadvertisement',
            name='сonditioning',
            field=models.CharField(blank=True, choices=[('local', 'Местное'), ('center', 'Центральное'), ('none', 'Нет')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='rentcommercialadvertisement',
            name='address',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='rentcommercialadvertisement',
            name='currency_deposit',
            field=models.CharField(choices=[('MZN', 'MZN'), ('USD', 'Доллар'), ('EUR', 'Евро')], default='mzn', max_length=3),
        ),
        migrations.AlterField(
            model_name='rentcommercialadvertisement',
            name='currency_rent_month',
            field=models.CharField(choices=[('MZN', 'MZN'), ('USD', 'Доллар'), ('EUR', 'Евро')], default='mzn', max_length=3),
        ),
        migrations.AlterField(
            model_name='rentcommercialadvertisement',
            name='currency_rent_month_per_m2',
            field=models.CharField(choices=[('MZN', 'MZN'), ('USD', 'Доллар'), ('EUR', 'Евро')], default='mzn', max_length=3),
        ),
        migrations.AlterField(
            model_name='rentcommercialadvertisement',
            name='currency_rent_year_per_m2',
            field=models.CharField(choices=[('MZN', 'MZN'), ('USD', 'Доллар'), ('EUR', 'Евро')], default='mzn', max_length=3),
        ),
        migrations.AlterField(
            model_name='rentcommercialadvertisement',
            name='infrastructure',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('carWash', 'Автомойка'), ('autoService', 'Автосервис'), ('pharmacy', 'Аптека'), ('clothingTailor', 'Ателье одежды'), ('atm', 'Банкомат'), ('swimmingPool', 'Бассейн'), ('buffet', 'Буфет'), ('exhibitionWarehouseComplex', 'Выставочно-складской комплекс'), ('hotel', 'Гостиница'), ('cafe', 'Кафе'), ('cinema', 'Кинотеатр'), ('conferenceHall', 'Конференц-зал'), ('medicalCenter', 'Медицинский центр'), ('miniMarket', 'Минимаркет'), ('notaryOffice', 'Нотариальная контора'), ('bankBranch', 'Отделение банка'), ('park', 'Парк'), ('restaurant', 'Ресторан'), ('beautySalon', 'Салон красоты'), ('warehouse', 'Складское помещение'), ('diningRoom', 'Столовая'), ('supermarket', 'Супермаркет'), ('shoppingArea', 'Торговая зона'), ('fitnessCenter', 'Фитнес-центр'), ('centralReception', 'Центральная рецепция')], max_length=281, null=True),
        ),
        migrations.AlterField(
            model_name='rentcommercialadvertisement',
            name='parkingCurreny',
            field=models.CharField(choices=[('MZN', 'MZN'), ('USD', 'Доллар'), ('EUR', 'Евро')], default='mzn', max_length=3),
        ),
        migrations.AlterField(
            model_name='rentcommercialadvertisement',
            name='prepayment',
            field=models.CharField(choices=[('4months', '4 мес'), ('5months', '5 мес'), ('6months', '6 мес'), ('7months', '7 мес'), ('8months', '8 мес'), ('9months', '9 мес'), ('10months', '10 мес'), ('11months', '11 мес'), ('1year', 'Год')], default='year', max_length=15),
        ),
        migrations.AlterField(
            model_name='rentcommercialadvertisement',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estatemaster.location'),
        ),
        migrations.AlterField(
            model_name='rentcommercialadvertisement',
            name='tax',
            field=models.CharField(blank=True, choices=[('VAT_included', 'Ндс включен'), ('tax_exempt', 'Ндс не облагается'), ('simplified_tax', 'Упрощенная налогообложения')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rentcommercialadvertisement',
            name='taxNumber',
            field=models.PositiveIntegerField(),
        ),
    ]
