# Generated by Django 5.1 on 2024-08-25 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estatemaster', '0050_rename_agebuild_rentcommercialadvertisement_buildingarea_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentcommercialadvertisement',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='rentdayadvertisement',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='rentlongadvertisement',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='salecommercialadvertisement',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
