# Generated by Django 5.1 on 2024-08-25 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estatemaster', '0051_rentcommercialadvertisement_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentcommercialadvertisement',
            name='promotion',
        ),
        migrations.RemoveField(
            model_name='saleresidential',
            name='promotion',
        ),
        migrations.AlterField(
            model_name='rentcommercialadvertisement',
            name='currency_deposit',
            field=models.CharField(choices=[('MZN', 'MZN'), ('USD', 'Доллар'), ('EUR', 'Евро')], default='MZN', max_length=3),
        ),
        migrations.AlterField(
            model_name='rentcommercialadvertisement',
            name='currency_rent_month',
            field=models.CharField(choices=[('MZN', 'MZN'), ('USD', 'Доллар'), ('EUR', 'Евро')], default='MZN', max_length=3),
        ),
        migrations.AlterField(
            model_name='rentcommercialadvertisement',
            name='currency_rent_month_per_m2',
            field=models.CharField(choices=[('MZN', 'MZN'), ('USD', 'Доллар'), ('EUR', 'Евро')], default='MZN', max_length=3),
        ),
        migrations.AlterField(
            model_name='rentcommercialadvertisement',
            name='currency_rent_year_per_m2',
            field=models.CharField(choices=[('MZN', 'MZN'), ('USD', 'Доллар'), ('EUR', 'Евро')], default='MZN', max_length=3),
        ),
        migrations.AlterField(
            model_name='rentcommercialadvertisement',
            name='parkingCurreny',
            field=models.CharField(choices=[('MZN', 'MZN'), ('USD', 'Доллар'), ('EUR', 'Евро')], default='MZN', max_length=3),
        ),
        migrations.AlterField(
            model_name='rentdayadvertisement',
            name='daily_price_currency',
            field=models.CharField(blank=True, choices=[('MZN', 'MZN'), ('USD', 'USD'), ('EUR', 'EUR')], default='MZN', max_length=3),
        ),
        migrations.AlterField(
            model_name='rentdayadvertisement',
            name='deposit_currency',
            field=models.CharField(blank=True, choices=[('MZN', 'MZN'), ('USD', 'USD'), ('EUR', 'EUR')], default='MZN', max_length=3),
        ),
        migrations.AlterField(
            model_name='rentlongadvertisement',
            name='currency',
            field=models.CharField(choices=[('MZN', 'MZN'), ('USD', 'USD'), ('EUR', 'EUR')], default='MZN', max_length=3),
        ),
        migrations.AlterField(
            model_name='rentlongadvertisement',
            name='currency_per_month',
            field=models.CharField(choices=[('MZN', 'MZN'), ('USD', 'USD'), ('EUR', 'EUR')], default='MZN', max_length=3),
        ),
        migrations.AlterField(
            model_name='salecommercialadvertisement',
            name='currency_per',
            field=models.CharField(choices=[('MZN', 'MZN'), ('USD', 'Доллар'), ('EUR', 'Евро')], default='MZN', max_length=3),
        ),
        migrations.AlterField(
            model_name='salecommercialadvertisement',
            name='currency_total',
            field=models.CharField(choices=[('MZN', 'MZN'), ('USD', 'Доллар'), ('EUR', 'Евро')], default='MZN', max_length=3),
        ),
        migrations.AlterField(
            model_name='salecommercialadvertisement',
            name='parkingCurreny',
            field=models.CharField(choices=[('MZN', 'MZN'), ('USD', 'Доллар'), ('EUR', 'Евро')], default='MZN', max_length=3),
        ),
        migrations.AlterField(
            model_name='saleresidential',
            name='currency',
            field=models.CharField(choices=[('MZN', 'MZN'), ('USD', 'Доллар'), ('EUR', 'Евро')], default='MZN', max_length=3),
        ),
    ]
