# Generated by Django 5.1 on 2024-08-25 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estatemaster', '0053_alter_rentdayadvertisement_leasetype_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentdayadvertisement',
            old_name='additional_phone',
            new_name='whatsApp',
        ),
        migrations.RemoveField(
            model_name='rentcommercialadvertisement',
            name='additional_phone',
        ),
        migrations.RemoveField(
            model_name='salecommercialadvertisement',
            name='additional_phone',
        ),
        migrations.AddField(
            model_name='rentcommercialadvertisement',
            name='whatsApp',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='salecommercialadvertisement',
            name='whatsApp',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
