# Generated by Django 5.1 on 2024-08-25 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estatemaster', '0054_rename_additional_phone_rentdayadvertisement_whatsapp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentcommercialadvertisement',
            name='heating',
            field=models.CharField(blank=True, choices=[('autonomous', 'Автономное'), ('central', 'Центральное'), ('none', 'Нет')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='rentcommercialadvertisement',
            name='parking',
            field=models.CharField(blank=True, choices=[('ground', 'Наземная'), ('multiLevel', 'Многоуровневая'), ('underground', 'Подземная'), ('in_roof', 'На крыше')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='rentcommercialadvertisement',
            name='сonditioning',
            field=models.CharField(blank=True, choices=[('local', 'Местное'), ('central', 'Центральное'), ('none', 'Нет')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='salecommercialadvertisement',
            name='parking',
            field=models.CharField(blank=True, choices=[('ground', 'Наземная'), ('multiLevel', 'Многоуровневая'), ('underground', 'Подземная'), ('in_roof', 'На крыше')], max_length=30, null=True),
        ),
    ]
