# Generated by Django 5.1 on 2024-08-26 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estatemaster', '0056_alter_salecommercialadvertisement_heating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentcommercialadvertisement',
            name='buildingArea',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='rentcommercialadvertisement',
            name='buildingType',
            field=models.CharField(blank=True, choices=[('administrative_building', 'Административное здание'), ('business_center', 'Бизнес-центр'), ('shopping_center', 'Торговый центр'), ('warehouse_complex', 'Складской комплекс'), ('industrial_park', 'Промышленный парк'), ('production_complex', 'Производственный комплекс'), ('multifunctional_complex', 'Многофункциональный комплекс'), ('logistics_complex', 'Логистический комплекс'), ('outlet', 'Аутлет'), ('other', 'Другое')], default='other', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rentcommercialadvertisement',
            name='category',
            field=models.CharField(blank=True, choices=[('valid', 'Действующее'), ('project', 'Проект'), ('under_construction', 'Строящееся')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='rentcommercialadvertisement',
            name='ceilingHeights',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='rentcommercialadvertisement',
            name='developer',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='rentcommercialadvertisement',
            name='fireExtinguishingSystem',
            field=models.CharField(blank=True, choices=[('hydrant', 'Гидрантная'), ('sprinkler', 'Спринклерная'), ('powder', 'Порошковая'), ('gas', 'Газовая'), ('alarm', 'Сигнализация'), ('false', 'Нет')], max_length=30),
        ),
        migrations.AlterField(
            model_name='rentcommercialadvertisement',
            name='floor',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rentcommercialadvertisement',
            name='floorsHouse',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rentcommercialadvertisement',
            name='furniture_c',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='rentcommercialadvertisement',
            name='managementCompany',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='rentcommercialadvertisement',
            name='pathType',
            field=models.CharField(choices=[('foot', 'Пешком'), ('transport', 'Транспорт')], default='foot', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rentcommercialadvertisement',
            name='planning',
            field=models.CharField(choices=[('open', 'Открытая'), ('corridor', 'Коридор'), ('cabinet', 'Кабинетная')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='rentcommercialadvertisement',
            name='plot',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='rentcommercialadvertisement',
            name='status',
            field=models.CharField(blank=True, choices=[('office_decoration', 'Офисная отделка'), ('finished', 'Под чистовую отделку'), ('major_repairs_required', 'Требуется капитальный ремонт'), ('cosmetic_repairs_required', 'Требуется косметический ремонт')], max_length=100),
        ),
        migrations.AlterField(
            model_name='rentcommercialadvertisement',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rentdayadvertisement',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rentlongadvertisement',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='salecommercialadvertisement',
            name='buildingArea',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='salecommercialadvertisement',
            name='buildingName',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='salecommercialadvertisement',
            name='buildingType',
            field=models.CharField(blank=True, choices=[('administrative_building', 'Административное здание'), ('business_center', 'Бизнес-центр'), ('shopping_center', 'Торговый центр'), ('warehouse_complex', 'Складской комплекс'), ('industrial_park', 'Промышленный парк'), ('production_complex', 'Производственный комплекс'), ('multifunctional_complex', 'Многофункциональный комплекс'), ('logistics_complex', 'Логистический комплекс'), ('outlet', 'Аутлет'), ('other', 'Другое')], default='other', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='salecommercialadvertisement',
            name='category',
            field=models.CharField(blank=True, choices=[('valid', 'Действующее'), ('project', 'Проект'), ('under_construction', 'Строящееся')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='salecommercialadvertisement',
            name='ceilingHeights',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='salecommercialadvertisement',
            name='developer',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='salecommercialadvertisement',
            name='fireExtinguishingSystem',
            field=models.CharField(blank=True, choices=[('hydrant', 'Гидрантная'), ('sprinkler', 'Спринклерная'), ('powder', 'Порошковая'), ('gas', 'Газовая'), ('alarm', 'Сигнализация'), ('false', 'Нет')], max_length=30),
        ),
        migrations.AlterField(
            model_name='salecommercialadvertisement',
            name='floor',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='salecommercialadvertisement',
            name='floorsHouse',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='salecommercialadvertisement',
            name='furniture_c',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='salecommercialadvertisement',
            name='managementCompany',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='salecommercialadvertisement',
            name='pathType',
            field=models.CharField(choices=[('foot', 'Пешком'), ('transport', 'Транспорт')], default='foot', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='salecommercialadvertisement',
            name='planning',
            field=models.CharField(choices=[('open', 'Открытая'), ('corridor', 'Коридор'), ('cabinet', 'Кабинетная')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='salecommercialadvertisement',
            name='plot',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='salecommercialadvertisement',
            name='status',
            field=models.CharField(blank=True, choices=[('office_decoration', 'Офисная отделка'), ('finished', 'Под чистовую отделку'), ('major_repairs_required', 'Требуется капитальный ремонт'), ('cosmetic_repairs_required', 'Требуется косметический ремонт')], max_length=100),
        ),
        migrations.AlterField(
            model_name='salecommercialadvertisement',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
