# Generated by Django 5.1 on 2024-08-27 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estatemaster', '0057_alter_rentcommercialadvertisement_buildingarea_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saleresidential',
            old_name='yaerBuilt',
            new_name='yearBuilt',
        ),
    ]
