# Generated by Django 5.1 on 2024-08-27 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estatemaster', '0058_rename_yaerbuilt_saleresidential_yearbuilt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saleresidential',
            old_name='whatsapp',
            new_name='whatsApp',
        ),
    ]
