# Generated by Django 5.1 on 2024-08-29 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estatemaster', '0061_photogroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisementphoto',
            name='photo_group',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='estatemaster.photogroup'),
        ),
    ]
