# Generated by Django 5.1 on 2024-08-31 09:55

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estatemaster', '0062_advertisementphoto_photo_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleresidential',
            name='apartmentEntrance',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('ramp', 'Пандус'), ('trashChute', 'Мусоропровод')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='saleresidential',
            name='viewFromWindow',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('outside', 'На улицу'), ('courtyard', 'Во двор'), ('atSea', 'На море')], max_length=23, null=True),
        ),
    ]
