# Generated by Django 5.1 on 2024-09-04 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estatemaster', '0065_alter_rentdayadvertisement_deposit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentcommercialadvertisement',
            name='agentBonus',
            field=models.CharField(choices=[('none', 'Нет'), ('fixed_sum', 'Фиксированная сумма'), ('percentage_of_deal', 'Процент от сделки')], default='false', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rentcommercialadvertisement',
            name='currency_rent_month_per_m2',
            field=models.CharField(choices=[('MZN', 'MZN'), ('USD', 'Доллар'), ('EUR', 'Евро')], default='MZN', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='rentcommercialadvertisement',
            name='currency_rent_year_per_m2',
            field=models.CharField(choices=[('MZN', 'MZN'), ('USD', 'Доллар'), ('EUR', 'Евро')], default='MZN', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='rentcommercialadvertisement',
            name='minimumLeaseTerm',
            field=models.PositiveIntegerField(blank=True, verbose_name='Минимальный срок аренды (в месяцах)'),
        ),
        migrations.AlterField(
            model_name='rentcommercialadvertisement',
            name='operatingCosts',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='rentcommercialadvertisement',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='rentcommercialadvertisement',
            name='rent_per_month',
            field=models.PositiveIntegerField(blank=True, verbose_name='Аренда в месяц'),
        ),
        migrations.AlterField(
            model_name='rentcommercialadvertisement',
            name='rentalType',
            field=models.CharField(blank=True, choices=[('long-term', 'Долгосрочная'), ('short-term', 'Краткосрочная')], max_length=50),
        ),
        migrations.AlterField(
            model_name='rentcommercialadvertisement',
            name='security_deposit',
            field=models.PositiveIntegerField(blank=True, verbose_name='Обеспечительный платеж'),
        ),
        migrations.AlterField(
            model_name='rentcommercialadvertisement',
            name='utilityPayment',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='rentlongadvertisement',
            name='currency',
            field=models.CharField(choices=[('MZN', 'MZN'), ('USD', 'USD'), ('EUR', 'EUR')], default='MZN', max_length=3),
        ),
        migrations.AlterField(
            model_name='rentlongadvertisement',
            name='deposit',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='rentlongadvertisement',
            name='prepaymentPeriod',
            field=models.CharField(blank=True, choices=[('1_month', 'За 1 месяц'), ('2_months', '2 месяца'), ('3_months', '3 месяца'), ('4+_months', '4+')], max_length=70),
        ),
    ]
