# Generated by Django 5.1 on 2024-09-04 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estatemaster', '0066_alter_rentcommercialadvertisement_agentbonus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisementphoto',
            name='isMain',
            field=models.BooleanField(default=False),
        ),
    ]
