# Generated by Django 5.1 on 2024-09-05 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estatemaster', '0067_advertisementphoto_ismain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentcommercialadvertisement',
            name='operatingCosts',
        ),
        migrations.AddField(
            model_name='rentcommercialadvertisement',
            name='operatingСosts',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
