# Generated by Django 5.1 on 2024-09-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estatemaster', '0068_remove_rentcommercialadvertisement_operatingcosts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentdayadvertisement',
            name='guestsNumber',
            field=models.PositiveIntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
