# Generated by Django 5.1 on 2024-09-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estatemaster', '0069_rentdayadvertisement_guestsnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentcommercialadvertisement',
            name='fireExtinguishingSystem',
            field=models.CharField(blank=True, choices=[('hydrant', 'Гидрантная'), ('sprinkler', 'Спринклерная'), ('powder', 'Порошковая'), ('gas', 'Газовая'), ('alarm', 'Сигнализация'), ('none', 'Нет')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='rentcommercialadvertisement',
            name='numberWetSpots',
            field=models.CharField(blank=True, choices=[(False, 'Нет'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('more_five', '5 и больше'), ('null', 'null')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='salecommercialadvertisement',
            name='fireExtinguishingSystem',
            field=models.CharField(blank=True, choices=[('hydrant', 'Гидрантная'), ('sprinkler', 'Спринклерная'), ('powder', 'Порошковая'), ('gas', 'Газовая'), ('alarm', 'Сигнализация'), ('none', 'Нет')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='salecommercialadvertisement',
            name='numberWetSpots',
            field=models.CharField(blank=True, choices=[(False, 'Нет'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('more_five', '5 и больше'), ('null', 'null')], max_length=50, null=True),
        ),
    ]
