# Generated by Django 5.1 on 2024-09-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estatemaster', '0070_alter_rentcommercialadvertisement_fireextinguishingsystem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentcommercialadvertisement',
            name='ceilingHeight',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='rentcommercialadvertisement',
            name='planning',
            field=models.CharField(choices=[('open', 'Открытая'), ('corridor', 'Коридор'), ('cabinet', 'Кабинетная'), (None, '')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='salecommercialadvertisement',
            name='ceilingHeight',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='salecommercialadvertisement',
            name='planning',
            field=models.CharField(choices=[('open', 'Открытая'), ('corridor', 'Коридор'), ('cabinet', 'Кабинетная'), (None, '')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='saleresidential',
            name='ceilingHeight',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
