# Generated by Django 5.1 on 2024-09-27 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estatemaster', '0075_alter_rentcommercialadvertisement_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='object_id',
            field=models.UUIDField(),
        ),
    ]
